---
- name: Asegurar que los servicios críticos estén encendidos (Auto-healing)
  hosts: all
  become: yes
  vars:
    servicios_criticos:
      - sshd
      - httpd

  tasks:

    - name: Obtener información de servicios disponibles
      service_facts:

    - name: Asegurar que los servicios existentes estén iniciados
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ servicios_criticos }}"
      when: "'{{ item }}.service' in ansible_facts.services"